// Maps a component slug to its source file basename under
// src/components/originals/. Generated from the ORIGINAL_COMPONENTS registry;
// display names do not reliably match file names, so this mapping is explicit.
export const ORIGINAL_SOURCE_FILES: Record<string, string> = {
  "aurora-login-card": "AuroraLoginCard",
  "spiral-gallery": "SpiralGallery",
  "falling-image-trail": "FallingImageTrail",
  "mask-page-transition": "MaskPageTransition",
  "counter-loader-hero": "CounterLoaderHero",
  "ink-reveal-cursor": "InkRevealCursor",
  "control-center-edit": "ControlCenterEdit",
  "physics-dock": "PhysicsDock",
  "coverflow-player": "CoverflowPlayer",
  "tip-splitter": "TipSplitter",
  "route-covered": "RouteCovered",
  "ev-range-widgets": "EvRangeWidgets",
  "mono-activity-heatmap": "mono-charts/MonoActivityHeatmap",
  "mono-rounded-spline-line": "mono-charts/MonoRoundedLineChart",
  "mono-rounded-pill-pillars": "mono-charts/MonoRoundedBarChart",
  "mono-curved-wave-area": "mono-charts/MonoRoundedAreaChart",
  "mono-rounded-donut-ring": "mono-charts/MonoRoundedDonutChart",
  "mono-hybrid-spline-bar": "mono-charts/MonoRoundedComposedChart",
  "mono-scatter-matrix": "mono-charts/MonoRoundedScatterChart",
  "mono-financial-candlesticks": "mono-charts/MonoRoundedCandlestickChart",
  "mono-tier-pyramid-stack": "mono-charts/MonoRoundedPyramidChart",
  "mono-radial-bar-group": "mono-charts/MonoRoundedRadialBarGroup",
  "mono-speedometer-gauge-arc": "mono-charts/MonoRoundedGaugeArc",
  "mono-step-progression": "mono-charts/MonoRoundedStepChart",
  "mono-stacked-tones-bar": "mono-charts/MonoRoundedStackedBarChart",
  "mono-polygon-web-radar": "mono-charts/MonoRoundedRadarChart",
  "mono-concentric-radial-rings": "mono-charts/MonoRoundedRadialGaugeChart",
  "mono-stage-funnel": "mono-charts/MonoRoundedFunnelChart",
  "mono-dot-matrix-heatmap": "mono-charts/MonoRoundedHeatmapChart",
  "mono-sparkline-telemetry": "mono-charts/MonoRoundedSparklineChart",
  "mono-bubble-clusters": "mono-charts/MonoRoundedBubbleChart",
  "mono-tile-treemap": "mono-charts/MonoRoundedTreemapChart",
  "mono-fluid-stream-wave": "mono-charts/MonoRoundedStreamChart",
  "mono-arc-meter-gauge": "mono-charts/MonoRoundedMeterChart",
  "mono-waterfall-steps": "mono-charts/MonoRoundedWaterfallChart",
  "mono-polar-radial-pillars": "mono-charts/MonoRoundedPolarChart",
  "magnetic-columns": "mono-charts/MagneticColumns",
  "rank-race": "mono-charts/RankRace",
  "hour-dial": "mono-charts/HourDial",
  "flow-funnel": "mono-charts/FlowFunnel",
  "cluster-field": "mono-charts/ClusterField",
  "layer-stack": "mono-charts/LayerStack",
  "velocity-gauge": "mono-charts/VelocityGauge",
  "ridge-lines": "mono-charts/RidgeLines",
  "drill-sunburst": "mono-charts/DrillSunburst",
  "spline-pulse": "mono-charts/SplinePulse",
  "pulse-rings": "mono-charts/PulseRings",
  "lens-range": "mono-charts/LensRange",
  "depth-book": "mono-charts/DepthBook",
  "dot-allocation": "mono-charts/DotAllocation",
  "live-signal": "mono-charts/LiveSignal",
  "mirror-bars": "mono-charts/MirrorBars",
  "share-strip": "mono-charts/ShareStrip",
  "orbit-segments": "mono-charts/OrbitSegments",
  "liquid-tank": "mono-charts/LiquidTank",
  "scrub-timeline": "mono-charts/ScrubTimeline",
  "pulse-radar": "mono-charts/PulseRadar",
  "ripple-matrix": "mono-charts/RippleMatrix",
  "rank-shuffle": "mono-charts/RankShuffle",
  "flow-stream": "mono-charts/FlowStream",
  "tilt-glow-panel": "mono-charts/TiltGlowPanel",
  "morph-views": "mono-charts/MorphViews",
};

export function sourceFileFor(slug: string): string | undefined {
  return ORIGINAL_SOURCE_FILES[slug];
}
