import type { ControlDef } from "./controls";
import type { Params } from "./effects";

export type OriginalEntry = {
  key: string;
  name: string;
  category: string;
  blurb: string;
  features: string[];
  controls: ControlDef[];
};

function defaultsFrom(controls: ControlDef[]): Params {
  const p: Params = {};
  for (const c of controls) p[c.key] = c.default;
  return p;
}

export const ORIGINALS: OriginalEntry[] = [
  {
    key: "cassette-menu",
    name: "Cassette Menu",
    category: "Navigation",
    blurb: "A retro cassette-tape menu overlay: tapes and a player slide in from below and fan out into place when the nav toggle is pressed, then snap back on close.",
    features: [
      "Two GSAP timelines (open/close) drive every element from one shared toggle state, with proper interrupt handling via overwrite: \"auto\"",
      "Tapes fan out horizontally on desktop and stack vertically on narrow containers, computed per-index inside the tween",
      "clip-path reveal on the overlay plus a bleeding radial 'bloom' circle gives the panel a soft analog feel",
      "A single speed control rescales every timeline duration and offset together, so the whole sequence stays in sync",
    ],
    controls: [
      { key: "overlayColor", label: "Overlay Color", type: "color", default: "#7b70f5", description: "Background color of the menu panel." },
      { key: "bloomColor", label: "Bloom Color", type: "color", default: "#beb9f9", description: "Color of the soft circular bloom behind the tapes." },
      { key: "accentColor", label: "Button Color", type: "color", default: "#f5e089", description: "Background color of the logo and menu toggle buttons." },
      { key: "heroText", label: "Hero Text", type: "text", default: "Slide One Out", description: "Heading shown behind the menu." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-google-sans-flex)", description: "Typeface used for the hero heading." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the hero heading." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 40, max: 220, step: 10, description: "Playback speed of the open/close timelines, as a percentage of the base rate." },
    ],
  },
  {
    key: "circular-gallery",
    name: "Circular Gallery",
    category: "Gallery",
    blurb: "A ring of photos tilts into an oval and spins on scroll, easing toward an idle drift and dimming everything but the hovered frame.",
    features: [
      "Ring position is computed per-frame from a tilted oval projection, not a CSS transform chain",
      "Scroll velocity accelerates the spin and decays back to an idle rate via simple easing, no ScrollTrigger needed",
      "Hover detection uses elementFromPoint against the live pointer position so it stays correct as the ring rotates under the cursor",
    ],
    controls: [
      { key: "centerLabel", label: "Center Label", type: "text", default: "origin", description: "Text in the badge at the centre of the ring." },
      { key: "speed", label: "Idle Speed", type: "slider", default: 100, min: 20, max: 250, step: 10, description: "Baseline rotation speed the ring eases back to." },
      { key: "tiltAngle", label: "Tilt Angle", type: "slider", default: -20, min: -45, max: 45, step: 5, description: "Tilt of the oval the images travel around." },
      { key: "hoverScale", label: "Hover Scale (%)", type: "slider", default: 110, min: 100, max: 140, step: 5, description: "Scale applied to the frame under the cursor." },
      { key: "dimStrength", label: "Dim Strength (%)", type: "slider", default: 65, min: 0, max: 90, step: 5, description: "How much non-hovered frames darken and desaturate." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-dm-sans), sans-serif", description: "Typeface used for the caption." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the caption." },
    ],
  },
  {
    key: "list-hover-cards",
    name: "List Hover Preview Cards",
    category: "Animations",
    blurb: "Hovering a line in a vertical list pops four polaroid-style images into view around it, following the cursor and nudging neighboring rows.",
    features: [
      "Neighboring row heights redistribute using inverse-distance weighting, so the whole list breathes around the hovered line",
      "Preview cards get a fresh random jitter position and rotation on every hover for a hand-scattered feel",
      "A default/alt label pair cross-fades with a blur + scale flourish instead of a plain opacity swap",
    ],
    controls: [
      { key: "bgColor", label: "Background", type: "color", default: "#0f0f0f", description: "Panel background color." },
      { key: "textColor", label: "Text Color", type: "color", default: "#ffffff", description: "Label and card border color." },
      { key: "growth", label: "Row Growth (%)", type: "slider", default: 50, min: 10, max: 100, step: 10, description: "How much the hovered row grows relative to its neighbors." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-host-grotesk), sans-serif", description: "Typeface used for the list labels." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the list labels." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 40, max: 200, step: 10, description: "Playback speed of every hover transition." },
    ],
  },
  {
    key: "grid-reveal-hero",
    name: "Grid Reveal Hero",
    category: "Animations",
    blurb: "A tile grid fades in with a progress marker hopping across it, then the whole grid collapses upward to reveal a headline built from sliding characters.",
    features: [
      "Grid density is computed from the container's own size, not the viewport, so it tiles cleanly at any preview size",
      "The progress marker uses GSAP Flip to hop between tiles instead of manually tweening position and size",
      "Title characters and subtitle lines use SplitText masks so they slide up from fully clipped, not just faded",
    ],
    controls: [
      { key: "accentColor", label: "Accent Color", type: "color", default: "#c4d600", description: "Tile and progress-marker accent color." },
      { key: "bgColor", label: "Backdrop", type: "color", default: "#e1e1e1", description: "Color behind the tile grid." },
      { key: "title", label: "Title", type: "text", default: "Frme", description: "Big headline revealed after the grid collapses." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-dm-sans), sans-serif", description: "Typeface used for all text." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of every text element." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of the whole reveal sequence." },
    ],
  },
  {
    key: "inline-hover-image",
    name: "Inline Hover Image",
    category: "Text",
    blurb: "A tiny dot sitting inline in a heading expands into an image card that tilts and drifts toward the cursor while hovered.",
    features: [
      "The card eases toward the pointer with its own lerp loop rather than snapping directly to cursor position",
      "3D tilt is derived from cursor offset within the card bounds and clamped to a max angle",
      "Collapses back to a single inline character width on mouse leave, so it never disturbs the surrounding text layout",
    ],
    controls: [
      { key: "images", label: "Images", type: "imageList", default: ["/inline-hover/img1.jpg", "/inline-hover/img2.jpg", "/inline-hover/img3.jpg"], description: "Images revealed by the inline spots." },
      { key: "textColor", label: "Text Color", type: "color", default: "#0f0f0f", description: "Heading and card border color." },
      { key: "tiltMax", label: "Max Tilt (deg)", type: "slider", default: 20, min: 5, max: 40, step: 5, description: "Maximum 3D tilt angle applied to the expanded card." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-barlow-condensed), sans-serif", description: "Typeface used for the heading." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the heading text." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 40, max: 200, step: 10, description: "Speed of the expand/collapse transitions." },
    ],
  },
  {
    key: "split-flicker-menu",
    name: "Split Flicker Menu",
    category: "Navigation",
    blurb: "A fullscreen nav list reveals itself with SplitText character masks staggered per row, while the toggle label flickers between Menu and Close.",
    features: [
      "Every label uses a SplitText character mask so each row unveils letter-by-letter instead of fading in as a block",
      "The toggle button's text swap plays a randomized per-character opacity flicker instead of a plain swap",
      "One shared timeline drives every row's index, divider, and label together, then just plays or reverses on toggle",
    ],
    controls: [
      { key: "brand", label: "Brand", type: "text", default: "Obscura", description: "Wordmark in the top bar." },
      { key: "menuLabel", label: "Menu Label", type: "text", default: "Menu", description: "Label on the menu toggle." },
      { key: "items", label: "Menu Items", type: "textList", default: ["Work", "Portfolio", "Retrospective", "Lens", "Selected", "Enquire"], description: "Links listed in the menu." },
      { key: "textColor", label: "Text Color", type: "color", default: "#e0e0ca", description: "Menu label and index color." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-dm-sans), sans-serif", description: "Typeface used for the menu labels." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the menu labels." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 40, max: 220, step: 10, description: "Playback speed of the open/close timeline." },
    ],
  },
  {
    key: "orbit-slider",
    name: "3D Orbit Slider",
    category: "Gallery",
    blurb: "A ring of photo panels orbits in 3D space, driven entirely by scroll, with the whole stage tilting toward the cursor and the centre panel always facing forward.",
    features: [
      "Panels are placed with rotateY + translateZ around a shared orbit, so perspective handles the sizing for free",
      "The centre panel counter-rotates against the ring so it always faces the camera flat while the ring spins behind it",
      "A single active-slide title/preview pair updates only when the nearest panel index actually changes",
    ],
    controls: [
      { key: "autoRotate", label: "Auto Rotate", type: "toggle", default: false, description: "Keep the ring gently spinning when idle. Off by default, matching the reference, which only turns on scroll." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 30, max: 220, step: 10, description: "Scroll sensitivity, and auto-rotation speed when Auto Rotate is on." },
      { key: "tiltMax", label: "Stage Tilt (deg)", type: "slider", default: 30, min: 0, max: 45, step: 5, description: "How far the whole stage tilts toward the cursor." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-commit-mono), monospace", description: "Typeface used for the title tag." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the title tag." },
    ],
  },
  {
    key: "gooey-text-reveal",
    name: "Gooey Text Reveal",
    category: "Text",
    blurb: "A heading's lines blur in from a heavy soft focus to fully sharp, run through an SVG gooey filter so the blur clumps rather than smears evenly.",
    features: [
      "An SVG feColorMatrix filter sharpens the alpha channel so the CSS blur reads as gooey clumps instead of a flat haze",
      "SplitText breaks the heading into masked lines so each line's blur layer can animate independently",
      "Pure CSS filter animation once split, with no canvas or WebGL involved",
    ],
    controls: [
      { key: "text", label: "Text", type: "text", default: "The Weight of Old Light", description: "Heading text that blurs into focus." },
      { key: "color", label: "Text Color", type: "color", default: "#f5f5f0", description: "Heading text color." },
      { key: "bgColor", label: "Background", type: "color", default: "#0f0f0f", description: "Panel background color." },
      { key: "gooey", label: "Gooey Filter", type: "toggle", default: true, description: "Toggle the SVG gooey filter on the blur." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-de-fonte-plus)", description: "Typeface used for the heading." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the heading." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 40, max: 220, step: 10, description: "Speed of the blur-to-sharp reveal." },
    ],
  },
  {
    key: "counter-reveal-hero",
    name: "Counter Reveal Hero",
    category: "Animations",
    blurb: "A loading screen counts to 100 while cycling a word and an image, then wipes away as the hero headline slides in from both sides and the thumbnail grows to fill the frame.",
    features: [
      "Counter, word cycle, and image cycle all ride the same timeline progress value instead of separate timers, so they stay in lockstep",
      "The thumbnail's fullscreen expansion is computed from its live bounding box, so it grows from wherever it actually sits",
      "Headline words are SplitText-masked and slide in from opposite edges depending on their row",
    ],
    controls: [
      { key: "eyebrow", label: "Eyebrow", type: "text", default: "Currently Developing", description: "Small label above the counter." },
      { key: "words", label: "Words", type: "textList", default: ["Studios", "Season", "Chamber", "Archive", "Vision"], description: "Words cycled by the counter." },
      { key: "accentColor", label: "Preloader Color", type: "color", default: "#272d2d", description: "Background color of the loading screen." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-neue-montreal)", description: "Typeface used for all text." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of every text element." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of the whole reveal sequence." },
    ],
  },
  {
    key: "dual-column-slider",
    name: "Dual Column Infinite Slider",
    category: "Gallery",
    blurb: "Two columns of images scroll in opposite directions, each slide wiping in and out with a clip-path reveal driven by wheel input.",
    features: [
      "Slides are created and destroyed on demand around the current scroll position, so the DOM stays small no matter how far you scroll",
      "Each column's reveal shape is a clip-path polygon animated purely by scroll offset, no per-slide tween needed",
      "An idle auto-drift keeps the columns moving gently until the first real scroll input takes over",
    ],
    controls: [
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 30, max: 220, step: 10, description: "Scroll sensitivity and auto-drift speed." },
      { key: "autoPlay", label: "Auto Drift", type: "toggle", default: true, description: "Keep the columns drifting when idle." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-inter), sans-serif", description: "Typeface used for the slide titles." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the slide titles." },
    ],
  },
  {
    key: "confetti-reveal",
    name: "Confetti Burst Reveal",
    category: "Animations",
    blurb: "A circular preloader wipes open, food photos burst outward and float, then fling off-screen as the hero fades in behind them.",
    features: [
      "A single timeline drives the circular wipe, the burst-out, the idle float loop, and the fling-off exit in sequence",
      "Each photo gets its own randomized float tween started only once it reaches its resting position",
      "The nav mark and hero accent circle scale in sync with the photos so the whole reveal reads as one gesture",
    ],
    controls: [
      { key: "bgColor", label: "Background", type: "color", default: "#17100a", description: "Preloader and canvas background color." },
      { key: "revealColor", label: "Accent Color", type: "color", default: "#f75828", description: "Color of the logo marks and hero accent circle." },
      { key: "heroText", label: "Hero Text", type: "text", default: "The table you will keep coming back to every week", description: "Headline shown once the preloader clears.", multiline: true },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-instrument-sans), sans-serif", description: "Typeface used for all text." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of every text element." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of the whole reveal sequence." },
    ],
  },
  {
    key: "perpetual-slider",
    name: "Perpetual Motion Slider",
    category: "Gallery",
    blurb: "An infinite drag/scroll slider where each panel's width grows exponentially with distance from center, so panels stream past faster the further they travel.",
    features: [
      "Panel edges are positioned with an exponential growth curve, not fixed widths, so the stream naturally accelerates outward",
      "Slide DOM nodes are recycled and reindexed every frame rather than created per scroll position",
      "Responds to wheel, touch drag, and pointer drag with the same eased scroll-target model",
    ],
    controls: [
      { key: "title", label: "Title", type: "text", default: "Perpetual Motion", description: "Headline shown over the slider." },
      { key: "autoPlay", label: "Auto Drift", type: "toggle", default: true, description: "Keep the stream drifting when idle." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-neue-montreal)", description: "Typeface used for the title." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the title." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 30, max: 220, step: 10, description: "Scroll and drag sensitivity multiplier." },
    ],
  },
  {
    key: "grid-deform-video",
    name: "Grid Deformation Video",
    category: "Background",
    blurb: "A looping video is rendered through a WebGL shader that displaces pixels around the cursor and splits color channels, like a heat-warped CRT feed.",
    features: [
      "Cursor velocity is written into a low-res data texture each frame, which a fragment shader reads to displace and chromatically split the video",
      "The displacement field relaxes back to zero on its own, so the ripple trails naturally without any manual decay loop",
      "The video plane always fills its container via a cover-fit computed from the video's real aspect ratio",
    ],
    controls: [
      { key: "strength", label: "Displacement Strength", type: "slider", default: 100, min: 20, max: 250, step: 10, description: "How far the cursor's motion pushes pixels around." },
      { key: "aberration", label: "Chromatic Split", type: "slider", default: 100, min: 0, max: 250, step: 10, description: "Strength of the RGB channel split at the displaced edges." },
      { key: "gridSize", label: "Grid Resolution", type: "slider", default: 25, min: 10, max: 50, step: 5, description: "Resolution of the displacement field grid." },
    ],
  },
  {
    key: "ascii-hand-footer",
    name: "ASCII Hand Footer",
    category: "Text",
    blurb: "Two hand photos are re-rendered as monospaced ASCII glyphs on canvas, with a hover trail that lights up clusters of characters as the cursor passes.",
    features: [
      "Each image is sampled into a low-res pixel grid once, mapping brightness to a ramp of ASCII characters",
      "Hovering finds the nearest character cell and lights up a short random walk of neighboring cells for a spreading trail effect",
      "Heading and link text reveal with SplitText masks while the hands drift gently with the cursor via a parallax loop",
    ],
    controls: [
      { key: "charColor", label: "Glyph Color", type: "color", default: "#803500", description: "Color of the resting ASCII characters." },
      { key: "hoverColor", label: "Hover Color", type: "color", default: "#ff6a00", description: "Highlight color for the hovered character trail." },
      { key: "headingLeft", label: "Left Heading", type: "text", default: "Blank", description: "Left-side footer headline." },
      { key: "headingRight", label: "Right Heading", type: "text", default: "Canvas", description: "Right-side footer headline." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-instrument-sans), sans-serif", description: "Typeface used for all text." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of every text element." },
    ],
  },
  {
    key: "magnetic-marquee",
    name: "Magnetic Spotlight Marquee",
    category: "Animations",
    blurb: "A background image marquee follows the cursor vertically with a soft lag, drifting between the top and bottom edges of the panel like a magnetized strip.",
    features: [
      "The marquee strip is cloned enough times to tile seamlessly, then scrolled with a wrapping modifier so the loop point is invisible",
      "Vertical position eases toward the cursor with its own lerp loop, independent of the horizontal scroll tween",
      "Foreground text sits in mix-blend-mode difference so it stays legible over the moving strip regardless of image brightness",
    ],
    controls: [
      { key: "images", label: "Marquee Images", type: "imageList", default: ["/magnetic-marquee/marquee-img-1.jpg", "/magnetic-marquee/marquee-img-2.jpg", "/magnetic-marquee/marquee-img-3.jpg", "/magnetic-marquee/marquee-img-4.jpg", "/magnetic-marquee/marquee-img-5.jpg", "/magnetic-marquee/marquee-img-6.jpg"], description: "Images tiled across the moving strip." },
      { key: "title", label: "Title", type: "text", default: "Spark Studio", description: "Main studio name." },
      { key: "subtitle", label: "Subtitle", type: "text", default: "Making stuff others try to copy", description: "Supporting tagline." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-instrument-serif), Georgia, serif", description: "Typeface used for the title and subtitle." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the title and subtitle." },
      { key: "speed", label: "Marquee Speed", type: "slider", default: 100, min: 30, max: 220, step: 10, description: "Horizontal scroll speed of the image strip." },
    ],
  },
  {
    key: "clip-mask-page-transition",
    name: "Clip Mask Page Transition",
    category: "Navigation",
    blurb: "Switching between pages sweeps four horizontal bands across the screen, lifts a wordmark up through them, then peels the bands away to reveal the next full-bleed image.",
    features: [
      "Four bands scale in from their left edge on a 0.075s stagger, then out toward their right edge, so the cover and the reveal read as opposite sweeps",
      "Page content is swapped at the exact moment the bands have the screen covered, so the swap is never seen",
      "Each word of the overlay wordmark rides up out of its own mask on a stagger, overlapping the band sweep rather than following it",
    ],
    controls: [
      { key: "images", label: "Page Images", type: "imageList", default: ["/clip-mask-transition/img1.jpg", "/clip-mask-transition/img2.jpg", "/clip-mask-transition/img3.jpg"], description: "Background image for each page." },
      { key: "brand", label: "Brand Name", type: "text", default: "Emberfall", description: "Wordmark shown in the nav bar." },
      { key: "overlayText", label: "Overlay Text", type: "text", default: "Your Brand Name", description: "Words that rise up while the bands cover the page." },
      { key: "overlayColor", label: "Overlay Color", type: "color", default: "#f2f0e6", description: "Colour of the bands that sweep across." },
      { key: "fontFamily", label: "Display Font", type: "font", default: "var(--font-instrument-serif), serif", description: "Typeface for the page title and the overlay wordmark." },
      { key: "navFont", label: "Nav Font", type: "font", default: "var(--font-instrument-sans), sans-serif", description: "Typeface used for the nav bar." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the nav and page title." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of each page transition." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: true, description: "Automatically cycle through pages." },
    ],
  },
  {
    key: "grid-wipe-transition",
    name: "Grid Wipe Transition",
    category: "Navigation",
    blurb: "A row of horizontal blocks sweeps across the screen from alternating edges to mask each page swap, with a wordmark unmasking in sync at the covered moment.",
    features: [
      "Blocks scale from zero width with alternating transform origins, so the sweep visually reverses direction between cover and uncover",
      "The brand wordmark uses a SplitText word mask timed to peek out only while the blocks fully cover the screen",
      "Each word of the overlay wordmark rides up out of its own mask on a stagger, overlapping the band sweep rather than following it",
    ],
    controls: [
      { key: "images", label: "Page Images", type: "imageList", default: ["/grid-wipe-transition/img1.jpg", "/grid-wipe-transition/img2.jpg", "/grid-wipe-transition/img3.jpg"], description: "Background image for each page." },
      { key: "brand", label: "Brand Name", type: "text", default: "Your Brand", description: "Wordmark revealed mid-transition." },
      { key: "gridColor", label: "Grid Color", type: "color", default: "#f2f0e6", description: "Fill color of the sweeping blocks." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-dm-sans), sans-serif", description: "Typeface used for the page title and wordmark." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the page title and wordmark." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of each page transition." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: true, description: "Automatically cycle through pages." },
    ],
  },
  {
    key: "outfit-reveal",
    name: "Archive Landing Reveal",
    category: "Animations",
    blurb: "A preloader cross-fades six clipped photos in and out around a counting-up percentage, then peels away as the giant headline and nav split-text in.",
    features: [
      "Photos animate both clip-path and scale together, so they iris open into full frames rather than just fading in",
      "The counter is a plain tweened number rather than a setInterval loop, so it can share easing with the rest of the timeline",
      "Nav links, headline, and footer labels all use SplitText masks so every reveal clips cleanly instead of just fading",
    ],
    controls: [
      { key: "images", label: "Preloader Images", type: "imageList", default: ["/outfit-reveal/img1.jpg", "/outfit-reveal/img2.jpg", "/outfit-reveal/img3.jpg", "/outfit-reveal/img4.jpg", "/outfit-reveal/img5.jpg", "/outfit-reveal/img6.jpg"], description: "Photos that fan out during the preloader." },
      { key: "brand", label: "Brand Name", type: "text", default: "Archive", description: "Wordmark used in the nav, hero, and preloader." },
      { key: "accentColor", label: "Ink Color", type: "color", default: "#141414", description: "Preloader background and hero text color." },
      { key: "bgColor", label: "Hero Background", type: "color", default: "#e0e2db", description: "Background color of the hero section." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-neue-montreal)", description: "Typeface used for all text." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of every text element." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of the whole reveal sequence." },
    ],
  },
  {
    key: "starfield-scroll",
    name: "Starfield Scroll",
    category: "Background",
    blurb: "A canvas starfield accelerates its streaks outward from a central hole as progress advances, while three headlines cross-fade and scale through the same timeline.",
    features: [
      "Each star is a gradient line stroke whose length, opacity, and travel distance are all derived from one shared progress value",
      "Star colors are drawn from a weighted palette so cooler hues dominate while warmer ones stay rare accents",
      "Headline words fade in and out with SplitText, staged so only one heading is legible at a time",
    ],
    controls: [
      { key: "headers", label: "Headlines", type: "textList", default: ["The whole galaxy opens up", "Leaving the known world behind", "And then everything goes still"], description: "The three cross-fading headlines.", max: 3 },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-dm-sans), sans-serif", description: "Typeface used for the headlines." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the headlines." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: true, description: "Sweep the timeline automatically back and forth." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 30, max: 220, step: 10, description: "Auto-play and scroll sensitivity multiplier." },
    ],
  },
  {
    key: "name-reveal-scroll",
    name: "Name Mask Reveal Scroll",
    category: "Text",
    blurb: "Project wordmarks unroll and roll back up via a vertical scale mask as progress advances, each one handing off to the next while a matching photo scales in and drifts away.",
    features: [
      "Every name and photo shares one continuous progress value, so handoffs between steps never desync",
      "The scale-mask reveal uses a different transform origin on the way in versus the way out, producing an unroll/reroll feel instead of a plain fade",
      "Photos scale up then drift upward on exit rather than simply disappearing, adding a sense of forward motion",
    ],
    controls: [
      { key: "images", label: "Project Images", type: "imageList", default: ["/name-reveal-scroll/project_img_1.jpg", "/name-reveal-scroll/project_img_2.jpg", "/name-reveal-scroll/project_img_3.jpg", "/name-reveal-scroll/project_img_4.jpg", "/name-reveal-scroll/project_img_5.jpg", "/name-reveal-scroll/project_img_6.jpg"], description: "One image per project step." },
      { key: "labels", label: "Names", type: "textList", default: ["INDEX", "AR-0472", "VX-2210", "KL-8834", "TN-1197", "MR-6650", "SC-3389"], description: "One label per name/step, first is the header." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-dm-sans), sans-serif", description: "Typeface used for the names." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the names." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: true, description: "Sweep through the sequence automatically." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 30, max: 220, step: 10, description: "Auto-play and scroll sensitivity multiplier." },
    ],
  },
  {
    key: "spotlight-zoom-scroll",
    name: "Spotlight Zoom Scroll",
    category: "Gallery",
    blurb: "A three-column photo collage zooms out and a corner logo scales down into place as progress advances, while a headline fades in word by word underneath.",
    features: [
      "Gallery scale, logo scale, and per-word headline opacity are all driven from the same 0-1 progress value with independently mapped ranges",
      "The logo's scale-down anchors from its own bottom-left corner, so it settles precisely into its resting nav position",
      "Headline words and the CTA button share one staggered fade window instead of separate timelines",
    ],
    controls: [
      { key: "images", label: "Gallery Images", type: "imageList", default: ["/spotlight-zoom-scroll/img1.jpg", "/spotlight-zoom-scroll/img2.jpg", "/spotlight-zoom-scroll/img3.jpg", "/spotlight-zoom-scroll/img4.jpg", "/spotlight-zoom-scroll/img5.jpg", "/spotlight-zoom-scroll/img6.jpg", "/spotlight-zoom-scroll/img7.jpg", "/spotlight-zoom-scroll/img8.jpg", "/spotlight-zoom-scroll/img9.jpg"], description: "Photos laid out across the three columns." },
      { key: "headline", label: "Headline", type: "text", default: "A living catalogue of images that shouldn't exist, collected frame by frame from the edge of the real.", description: "Copy revealed word by word.", multiline: true },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-plus-jakarta-sans), sans-serif", description: "Typeface used for the headline." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the headline." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: true, description: "Sweep the zoom automatically." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 30, max: 220, step: 10, description: "Auto-play and scroll sensitivity multiplier." },
    ],
  },
  {
    key: "slit-reveal-scroll",
    name: "Slit Reveal Scroll",
    category: "Animations",
    blurb: "A full-bleed hero pinches into a thin vertical slit, rotates and scales away to reveal a two-column background, then an outro wipes in from top and bottom with a masked closing line.",
    features: [
      "Four distinct phases share one progress value, each mapped to its own sub-range so they chain without gaps or overlaps",
      "The closing slit is a clip-path polygon animated on two edges independently, not a single width tween",
      "The outro's two images wipe in from opposite edges via independent clip-path bands, meeting in the middle",
    ],
    controls: [
      { key: "accentColor", label: "Accent Color", type: "color", default: "#e12c1a", description: "Overlay wash and heading accent color." },
      { key: "outroText", label: "Outro Text", type: "text", default: "You become the shape that the light finally learns to find.", description: "Closing line revealed at the end.", multiline: true },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-neue-montreal)", description: "Typeface used for all text." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of every text element." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: false, description: "Off matches the reference, which only moves with the scroll. Sweep through the phases automatically." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 30, max: 220, step: 10, description: "Auto-play and scroll sensitivity multiplier." },
    ],
  },
  {
    key: "stroke-draw-reveal",
    name: "Stroke Draw Reveal",
    category: "Text",
    blurb: "A field of thick curved strokes draws itself on out of sequence to fully cover a message, holds, then draws off again in reverse order to reveal the payoff line: with sparkles popping as the cover completes.",
    features: [
      "Each stroke is drawn using a stroke-dashoffset tween, with the draw order deliberately non-linear so the cover feels organic rather than mechanical",
      "A darker outline copy sits beneath each colored stroke, giving every curve a hand-inked edge without an SVG filter",
      "Sparkles pop in with a back-out ease exactly as the covering strokes finish, timed off the same shared timeline",
    ],
    controls: [
      { key: "beforeTitle", label: "Before Headline", type: "text", default: "Wait for it", description: "Headline shown while the strokes cover the message." },
      { key: "beforeBody", label: "Before Body", type: "text", default: "The good part is closer, just one scroll away.", description: "Supporting line shown before the reveal." },
      { key: "afterTitle", label: "After Headline", type: "text", default: "There it is", description: "Headline revealed once the strokes draw off." },
      { key: "afterBody", label: "After Body", type: "text", default: "Clean, sharp, and right when you needed it.", description: "Supporting line shown after the reveal." },
      { key: "strokeColor", label: "Stroke Color", type: "color", default: "#fff280", description: "Fill color of the drawn strokes." },
      { key: "bgFrom", label: "Background Start", type: "color", default: "#ff668c", description: "Left side of the background gradient." },
      { key: "bgTo", label: "Background End", type: "color", default: "#fff280", description: "Right side of the background gradient." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-barlow-condensed), sans-serif", description: "Typeface used for the headline." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of every text element." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: true, description: "Sweep the cover/reveal automatically." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 30, max: 220, step: 10, description: "Auto-play and scroll sensitivity multiplier." },
    ],
  },
  {
    key: "grid-shutter-transition",
    name: "Grid Shutter Transition",
    category: "Navigation",
    blurb: "Switching pages closes a grid of blocks across the screen, alternate rows sweeping in from opposite ends, then reopens them the same way onto the next full-bleed page.",
    features: [
      "Every row animates at once, but odd rows stagger from the right and even rows from the left, which is what gives the shutter its woven feel",
      "Blocks are measured off the live container and rebuilt on resize, each a pixel oversized so no seams show between them",
      "The page swaps at the moment the grid has the screen covered, so the change is never seen",
    ],
    controls: [
      { key: "images", label: "Page Images", type: "imageList", default: ["/grid-shutter/img1.jpg", "/grid-shutter/img2.jpg", "/grid-shutter/img3.jpg"], description: "Background image for each page." },
      { key: "pages", label: "Page Names", type: "textList", default: ["Genesis", "Cascade", "Orbit"], description: "Title and nav label for each page." },
      { key: "brand", label: "Brand Name", type: "text", default: "Duskfield", description: "Wordmark in the top left." },
      { key: "shutterColor", label: "Shutter Color", type: "color", default: "#f2f0e6", description: "Colour of the blocks that close over the page." },
      { key: "rows", label: "Rows", type: "slider", default: 4, min: 1, max: 12, step: 1, description: "How many rows the shutter grid is divided into." },
      { key: "columns", label: "Columns", type: "slider", default: 16, min: 2, max: 40, step: 1, description: "Blocks per row. More columns means a finer sweep." },
      { key: "fontFamily", label: "Display Font", type: "font", default: "var(--font-instrument-serif), serif", description: "Typeface for the page title." },
      { key: "navFont", label: "Nav Font", type: "font", default: "var(--font-instrument-sans), sans-serif", description: "Typeface used for the nav bar." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the title and nav." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of the transition." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: true, description: "Cycle through the pages on their own." },
    ],
  },
  {
    key: "dissolve-image-reveal",
    name: "Dissolve Image Reveal",
    category: "Gallery",
    blurb: "Scrolling wipes each image away along a band of flickering characters, a solid core of glyphs at the wipe line scattering out into noise at its edges.",
    features: [
      "The wipe edge and the character band share one position, so the glyphs always sit exactly on the seam between two images",
      "Each cell's noise comes from a hash of its own row and column, so the scatter pattern is stable rather than reshuffling every frame",
      "Cells near the centre of the band scatter least, leaving a solid core that frays into loose characters at the edges",
    ],
    controls: [
      { key: "images", label: "Images", type: "imageList", default: ["/dissolve-reveal/img-1.jpg", "/dissolve-reveal/img-2.jpg", "/dissolve-reveal/img-3.jpg", "/dissolve-reveal/img-4.jpg", "/dissolve-reveal/img-5.jpg"], description: "Images stacked in reveal order." },
      { key: "dissolveColor", label: "Dissolve Color", type: "color", default: "#ff6426", description: "Colour of the character cells in the band." },
      { key: "cellSize", label: "Cell Size", type: "slider", default: 16, min: 8, max: 48, step: 2, description: "Size of each character cell in pixels." },
      { key: "spreadAbove", label: "Spread Above", type: "slider", default: 25, min: 5, max: 60, step: 5, description: "How far the band reaches above the wipe line." },
      { key: "spreadBelow", label: "Spread Below", type: "slider", default: 25, min: 5, max: 60, step: 5, description: "How far the band reaches below the wipe line." },
      { key: "scatterIntensity", label: "Scatter", type: "slider", default: 15, min: 0, max: 60, step: 5, description: "How loosely cells scatter away from the band." },
      { key: "visibilityThreshold", label: "Density", type: "slider", default: 65, min: 20, max: 100, step: 5, description: "How densely the cells fill the band." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-dm-mono), monospace", description: "Typeface used for the dissolve characters." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Scroll sensitivity of the reveal." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: false, description: "Off matches the reference, which only moves with the scroll." },
    ],
  },
  {
    key: "mosaic-flip-hover",
    name: "Mosaic Flip Hover",
    category: "Gallery",
    blurb: "A wall of tiles drifts in depth on its own, then flips in a wave out from the centre to turn over into the next project's image as you move down the list.",
    features: [
      "Every tile is a 3D box whose faces each carry their own slice of the picture, so the wall reads as one image rather than a grid of thumbnails",
      "The incoming image is painted onto whichever face is currently turned away, so the swap itself is never visible",
      "Tiles drift to random depths on independent loops, staggered on start so the wall never pulses in unison",
    ],
    controls: [
      { key: "images", label: "Project Images", type: "imageList", default: ["/mosaic-flip/img1.jpg", "/mosaic-flip/img2.jpg", "/mosaic-flip/img3.jpg", "/mosaic-flip/img4.jpg", "/mosaic-flip/img5.jpg", "/mosaic-flip/img6.jpg"], description: "One image per project in the list." },
      { key: "labels", label: "Project Names", type: "textList", default: ["NX-09", "1997 Hallway Tape", "Deep Space", "Sleep Phase Anomaly", "Still-life.mov", "Monoform\u2122"], description: "Hover targets listed in the corner." },
      { key: "idleImage", label: "Idle Image", type: "image", default: "/mosaic-flip/default.jpg", description: "Shown when nothing is hovered." },
      { key: "background", label: "Background", type: "color", default: "#171717", description: "Colour behind the tile wall." },
      { key: "tileEdge", label: "Tile Edge", type: "color", default: "#222222", description: "Colour of the top and bottom faces of each tile." },
      { key: "tilesX", label: "Columns", type: "slider", default: 12, min: 4, max: 20, step: 1, description: "Tiles across the wall." },
      { key: "tilesY", label: "Rows", type: "slider", default: 9, min: 3, max: 16, step: 1, description: "Tiles down the wall." },
      { key: "tileSize", label: "Tile Size", type: "slider", default: 60, min: 30, max: 100, step: 5, description: "Size of each tile in pixels." },
      { key: "breatheDepth", label: "Drift Depth", type: "slider", default: 40, min: 0, max: 120, step: 10, description: "How far tiles drift toward and away from you." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-dm-mono), monospace", description: "Typeface for the project list." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the project list." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Speed of the flip and the idle drift." },
    ],
  },
  {
    key: "lens-zoom-scroll",
    name: "Lens Zoom Scroll",
    category: "Animations",
    blurb: "Scrolling sweeps light across the lenses of a drawn illustration, fades a photograph in behind the glass, then dives the whole scene 22x into one lens as the headline assembles word by word.",
    features: [
      "Each lens in the artwork is turned into a clipping mask at runtime, so the photograph appears only through the glass",
      "Glare bands finish their sweep at 75% of the scroll, handing off to the zoom rather than competing with it",
      "The zoom runs from a fixed focus point on the artwork, so the dive lands inside a single lens no matter the screen size",
    ],
    controls: [
      { key: "headline", label: "Headline", type: "text", default: "Insert Something Wildly Impressive Right Here", description: "Words that assemble during the zoom." },
      { key: "lensImage", label: "Lens Image", type: "image", default: "/lens-zoom/img.jpg", description: "Photograph revealed inside the lenses." },
      { key: "background", label: "Background", type: "color", default: "#eb5e55", description: "Colour behind the illustration." },
      { key: "glaresPerLens", label: "Glares Per Lens", type: "slider", default: 2, min: 1, max: 5, step: 1, description: "How many light bands sweep each lens." },
      { key: "finalZoomScale", label: "Zoom Scale", type: "slider", default: 22, min: 5, max: 40, step: 1, description: "How far the scene dives into the lens." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-barlow-condensed), sans-serif", description: "Typeface used for the headline." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the headline." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Scroll sensitivity of the zoom." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: false, description: "Off matches the reference, which only moves with the scroll." },
    ],
  },
  {
    key: "accordion-frames",
    name: "Accordion Frames",
    category: "Gallery",
    blurb: "A row of thin slivers where the one under the cursor opens to full width and the rest close, with a full-height rule tracking whichever frame is open.",
    features: [
      "Each panel's position is measured from every panel to its left, so the row stays centred whichever frame is open",
      "Images hold the open width at all times, so a closed panel is a slice of the picture rather than a squeezed copy",
      "The focus rule shares the panels' transition, so it travels with the frame instead of snapping to it",
    ],
    controls: [
      { key: "images", label: "Images", type: "imageList", default: ["/accordion-frames/spotlight-1.jpg", "/accordion-frames/spotlight-2.jpg", "/accordion-frames/spotlight-3.jpg", "/accordion-frames/spotlight-4.jpg", "/accordion-frames/spotlight-5.jpg", "/accordion-frames/spotlight-6.jpg", "/accordion-frames/spotlight-7.jpg", "/accordion-frames/spotlight-8.jpg", "/accordion-frames/spotlight-9.jpg", "/accordion-frames/spotlight-10.jpg", "/accordion-frames/spotlight-11.jpg", "/accordion-frames/spotlight-12.jpg", "/accordion-frames/spotlight-13.jpg", "/accordion-frames/spotlight-14.jpg", "/accordion-frames/spotlight-15.jpg", "/accordion-frames/spotlight-16.jpg", "/accordion-frames/spotlight-17.jpg", "/accordion-frames/spotlight-18.jpg", "/accordion-frames/spotlight-19.jpg", "/accordion-frames/spotlight-20.jpg"], description: "One image per frame." },
      { key: "background", label: "Background", type: "color", default: "#0f0f0f", description: "Colour behind the row." },
      { key: "indicatorColor", label: "Indicator Color", type: "color", default: "#ffffff", description: "Colour of the focus rule." },
      { key: "collapsedWidth", label: "Closed Width", type: "slider", default: 20, min: 6, max: 60, step: 2, description: "Width of a closed frame in pixels." },
      { key: "expandedWidth", label: "Open Width", type: "slider", default: 400, min: 150, max: 700, step: 10, description: "Width of the open frame in pixels." },
      { key: "panelGap", label: "Gap", type: "slider", default: 5, min: 0, max: 30, step: 1, description: "Space between frames in pixels." },
      { key: "panelHeight", label: "Height", type: "slider", default: 400, min: 150, max: 700, step: 10, description: "Height of the row in pixels." },
      { key: "duration", label: "Speed", type: "slider", default: 100, min: 50, max: 250, step: 10, description: "Speed of the open and close." },
    ],
  },
  {
    key: "magnetic-cards",
    name: "Magnetic Cards",
    category: "Animations",
    blurb: "A fanned row of cards that scatters away from a moving cursor and springs back, each card dragging its neighbours along with it.",
    features: [
      "Cards react to how fast the cursor moves rather than merely where it is, so a slow pass leaves them alone and a flick scatters them",
      "Force carries to neighbours with a sharp falloff along the stack, which makes the row move like one piece of fabric",
      "A spring with friction returns every card to its resting offset and angle, so the arrangement is never lost",
    ],
    controls: [
      { key: "images", label: "Card Images", type: "imageList", default: ["/magnetic-cards/card-img-1.jpg", "/magnetic-cards/card-img-2.jpg", "/magnetic-cards/card-img-3.jpg", "/magnetic-cards/card-img-4.jpg"], description: "One image per card." },
      { key: "background", label: "Background", type: "color", default: "#141414", description: "Colour behind the cards." },
      { key: "cardSize", label: "Card Size", type: "slider", default: 250, min: 120, max: 400, step: 10, description: "Width and height of each card in pixels." },
      { key: "proximityRadius", label: "Reach", type: "slider", default: 500, min: 150, max: 900, step: 50, description: "How close the cursor must be to move a card." },
      { key: "pushForce", label: "Push Force", type: "slider", default: 10, min: 2, max: 30, step: 1, description: "How hard the cursor throws the cards." },
      { key: "tiltAmount", label: "Tilt", type: "slider", default: 10, min: 0, max: 40, step: 2, description: "How much cards rotate as they are pushed." },
      { key: "neighborInfluence", label: "Neighbour Pull", type: "slider", default: 20, min: 0, max: 60, step: 5, description: "How much a card drags the cards beside it." },
      { key: "springStiffness", label: "Spring", type: "slider", default: 5, min: 1, max: 20, step: 1, description: "How strongly cards are pulled back to rest." },
      { key: "bounceFriction", label: "Friction", type: "slider", default: 85, min: 60, max: 98, step: 1, description: "How quickly the bouncing settles." },
    ],
  },
  {
    key: "steelworks-reveal",
    name: "Steelworks Reveal",
    category: "Animations",
    blurb: "A loading bar fills and empties, the curtain lifts, and a row of tilted frames slides in before the outer ones clear the screen and the middle one opens into the full hero.",
    features: [
      "One timeline runs the whole load: bar, curtain, the sliding row, and the copy, each step overlapping the last rather than waiting for it",
      "The bar fills from its left edge then empties from its right, so it reads as loading rather than looping",
      "Every line of copy rides up out of its own mask on a stagger, starting while the hero frame is still opening",
    ],
    controls: [
      { key: "images", label: "Frame Images", type: "imageList", default: ["/steelworks-reveal/img-1.jpg", "/steelworks-reveal/img-2.jpg", "/steelworks-reveal/img-3.jpg", "/steelworks-reveal/img-4.jpg", "/steelworks-reveal/img-5.jpg"], description: "Frames that slide in. The middle one becomes the hero." },
      { key: "headline", label: "Headline", type: "text", default: "We design objects that carry the weight of their own conviction, where every curve and joint exists not for beauty but because the material demanded it.", description: "Hero copy, revealed line by line." },
      { key: "brand", label: "Brand", type: "text", default: "Foundry & Form", description: "Wordmark in the top left." },
      { key: "tagline", label: "Tagline", type: "text", default: "Industrial Design Consultancy", description: "Line under the wordmark." },
      { key: "navItems", label: "Nav Items", type: "textList", default: ["Work", "Catalogue", "About"], description: "Links in the top right." },
      { key: "contactLabel", label: "Contact Label", type: "text", default: "Say Hello", description: "Label above the contact links." },
      { key: "contactLinks", label: "Contact Links", type: "textList", default: ["info@foundryandform.com", "View Enquiries"], description: "Links at the bottom of the hero." },
      { key: "background", label: "Background", type: "color", default: "#0f0f0f", description: "Colour of the curtain and page." },
      { key: "preloaderColor", label: "Loading Bar", type: "color", default: "#ffffff", description: "Colour of the loading bar." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-dm-sans), sans-serif", description: "Typeface used throughout." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of all copy." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of the reveal." },
    ],
  },
  {
    key: "scroll-tunnel",
    name: "3D Scroll Tunnel",
    category: "Gallery",
    blurb: "Images ringed around an endless corridor rush past the camera as you scroll, fading up out of the dark and blacking out again as they pass.",
    features: [
      "Layers wrap through the tunnel's depth on a modulo, so the corridor recycles forever with a fixed number of elements",
      "Each layer's darkness is a curve of its depth, squared on approach, so images emerge from black rather than popping in",
      "Layers past the camera are hidden outright rather than merely transparent, keeping the paint cost flat however long you scroll",
    ],
    controls: [
      { key: "images", label: "Images", type: "imageList", default: ["/scroll-tunnel/img1.jpg", "/scroll-tunnel/img2.jpg", "/scroll-tunnel/img3.jpg", "/scroll-tunnel/img4.jpg", "/scroll-tunnel/img5.jpg", "/scroll-tunnel/img6.jpg", "/scroll-tunnel/img7.jpg", "/scroll-tunnel/img8.jpg", "/scroll-tunnel/img9.jpg", "/scroll-tunnel/img10.jpg", "/scroll-tunnel/img11.jpg", "/scroll-tunnel/img12.jpg"], description: "Images ringed around the tunnel, four to a layer." },
      { key: "background", label: "Background", type: "color", default: "#000000", description: "Colour of the void and the fade-out." },
      { key: "layerGap", label: "Layer Gap", type: "slider", default: 2500, min: 800, max: 5000, step: 100, description: "Depth between rings of images." },
      { key: "scrollSpeed", label: "Scroll Speed", type: "slider", default: 200, min: 50, max: 500, step: 10, description: "How fast scrolling travels the tunnel." },
      { key: "smoothing", label: "Smoothing", type: "slider", default: 7, min: 1, max: 30, step: 1, description: "How much the motion lags behind the scroll." },
      { key: "itemWidth", label: "Image Width", type: "slider", default: 180, min: 80, max: 320, step: 10, description: "Width of each image in pixels." },
      { key: "itemHeight", label: "Image Height", type: "slider", default: 220, min: 100, max: 400, step: 10, description: "Height of each image in pixels." },
      { key: "radiusX", label: "Ring Width", type: "slider", default: 400, min: 150, max: 700, step: 10, description: "How far images sit from the centre horizontally." },
      { key: "radiusY", label: "Ring Height", type: "slider", default: 280, min: 100, max: 600, step: 10, description: "How far images sit from the centre vertically." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: true, description: "Drift down the tunnel without scrolling." },
    ],
  },
  {
    key: "creative-clutter",
    name: "Creative Clutter",
    category: "Animations",
    blurb: "A desk of scattered objects that rearranges itself between a messy pile, a tidy grid, and a notebook spread, every piece flying to its new place at once.",
    features: [
      "Each mode is a full set of positions rather than a set of moves, so any arrangement can animate into any other",
      "GSAP's Flip records where every object is, the layout snaps to the new mode, and the difference is animated back",
      "Positions are percentages of the desk, so the arrangements hold their composition at any size",
    ],
    controls: [
      { key: "title", label: "Title", type: "text", default: "Creative Clutter", description: "Heading on the desk." },
      { key: "body", label: "Body", type: "text", default: "The best ideas live somewhere between a coffee stain and a half-open folder, scattered things have a way of finding others when you stop trying to organize.", description: "Supporting copy under the heading." },
      { key: "background", label: "Background", type: "color", default: "#e8e6df", description: "Colour of the desk." },
      { key: "textColor", label: "Text Color", type: "color", default: "#141414", description: "Colour of the copy and the mode buttons." },
      { key: "itemScale", label: "Object Size", type: "slider", default: 100, min: 40, max: 150, step: 5, description: "Relative size of every object on the desk." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-dm-sans), sans-serif", description: "Typeface for the copy." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the copy." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Speed of the rearrangement." },
    ],
  },
  {
    key: "ascii-image-reveal",
    name: "ASCII Image Reveal",
    category: "Gallery",
    blurb: "Photographs resolve out of a field of ASCII characters, cells popping in at random and the darkest ones rolling through noise before they settle.",
    features: [
      "Each image is sampled to a character grid by luminance, so the type itself carries the picture before the photo appears",
      "Only cells past a density threshold scramble, so highlights land immediately and shadows churn, which is what gives the reveal its texture",
      "Cells arrive in shuffled order rather than by row, and the photo fades in only once every cell has settled",
    ],
    controls: [
      { key: "images", label: "Images", type: "imageList", default: ["/ascii-reveal/img1.jpg", "/ascii-reveal/img2.jpg", "/ascii-reveal/img3.jpg", "/ascii-reveal/img4.jpg", "/ascii-reveal/img5.jpg", "/ascii-reveal/img6.jpg", "/ascii-reveal/img7.jpg", "/ascii-reveal/img8.jpg", "/ascii-reveal/img9.jpg", "/ascii-reveal/img10.jpg", "/ascii-reveal/img11.jpg", "/ascii-reveal/img12.jpg", "/ascii-reveal/img13.jpg", "/ascii-reveal/img14.jpg", "/ascii-reveal/img15.jpg"], description: "Photographs to resolve out of the characters." },
      { key: "characters", label: "Character Ramp", type: "text", default: "........:::=+xX#0369", description: "Light to dark. Everything after the last dot is treated as dark and scrambles." },
      { key: "background", label: "Background", type: "color", default: "#111111", description: "Colour behind the characters." },
      { key: "inkColor", label: "Character Color", type: "color", default: "#c8c8c8", description: "Colour of the characters." },
      { key: "columns", label: "Columns", type: "slider", default: 25, min: 10, max: 60, step: 1, description: "Character columns per image. More means finer detail." },
      { key: "fontSize", label: "Character Size", type: "slider", default: 14, min: 8, max: 28, step: 1, description: "Size of each character in pixels." },
      { key: "imageStagger", label: "Image Stagger", type: "slider", default: 100, min: 0, max: 400, step: 20, description: "Delay between images starting, in milliseconds." },
      { key: "cellAppear", label: "Cell Rate", type: "slider", default: 2, min: 1, max: 20, step: 1, description: "Milliseconds between cells appearing." },
      { key: "scrambleCount", label: "Scramble Steps", type: "slider", default: 10, min: 1, max: 30, step: 1, description: "How many times a dark cell rerolls before settling." },
      { key: "scrambleSpeed", label: "Scramble Speed", type: "slider", default: 100, min: 30, max: 300, step: 10, description: "Milliseconds between rerolls." },
    ],
  },
  {
    key: "physics-tag-hover",
    name: "Physics Tag Hover",
    category: "Animations",
    blurb: "Hovering a service opens the row on an elastic bounce, slides its images up, and drops a handful of pill tags that fall and pile up on real physics.",
    features: [
      "Tags are real rigid bodies in a Matter.js world, so they tumble, collide and settle differently every time",
      "Floor and walls are built from the row's live size, so the pile always lands on the word rather than the container edge",
      "Tags only start dropping once the row has begun opening, and are cleared on leave so no engine is left running",
    ],
    controls: [
      { key: "background", label: "Background", type: "color", default: "#171717", description: "Colour behind the services." },
      { key: "nameColor", label: "Name Color", type: "color", default: "#ff3831", description: "Colour of a resting service name." },
      { key: "activeNameColor", label: "Active Name Color", type: "color", default: "#ffffd9", description: "Colour of the hovered service name." },
      { key: "tagColor", label: "Tag Color", type: "color", default: "#ffffd9", description: "Border and text colour of the falling tags." },
      { key: "gravity", label: "Gravity", type: "slider", default: 2, min: 1, max: 6, step: 1, description: "How hard the tags fall." },
      { key: "collapsedHeight", label: "Closed Height", type: "slider", default: 160, min: 80, max: 260, step: 10, description: "Height of a resting row in pixels." },
      { key: "expandedHeight", label: "Open Height", type: "slider", default: 400, min: 200, max: 600, step: 20, description: "Height of the hovered row in pixels." },
      { key: "fontFamily", label: "Name Font", type: "font", default: "var(--font-barlow-condensed), sans-serif", description: "Typeface for the service names." },
      { key: "tagFont", label: "Tag Font", type: "font", default: "var(--font-instrument-serif), serif", description: "Typeface for the falling tags." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the names and tags." },
    ],
  },
  {
    key: "smudge-revealer",
    name: "Smudge Revealer",
    category: "Animations",
    blurb: "Dragging the cursor smears away the top layer to expose the message underneath, the smear swelling and dissolving behind you.",
    features: [
      "Each frame stamps a circle into an SVG mask, and a goo filter welds overlapping stamps into one shape so a fast drag reads as a smear rather than a string of dots",
      "Stamp size comes from the gap the smoothing has yet to close, so faster movement paints wider",
      "Every stamp swells then shrinks to nothing on its own timeline, so the opening heals behind the cursor",
    ],
    controls: [
      { key: "frontText", label: "Front Text", type: "text", default: "Dig in", description: "Large text on the covering layer." },
      { key: "backText", label: "Hidden Text", type: "text", default: "The things worth finding are never on the surface. They live in the parts you almost scrolled past.", description: "Message revealed by the smear." },
      { key: "frontBackground", label: "Front Background", type: "color", default: "#2a2b2a", description: "Colour of the covering layer." },
      { key: "frontColor", label: "Front Text Color", type: "color", default: "#edf2ed", description: "Colour of the covering text." },
      { key: "backBackground", label: "Hidden Background", type: "color", default: "#cbd4c2", description: "Colour behind the smear." },
      { key: "backColor", label: "Hidden Text Color", type: "color", default: "#323332", description: "Colour of the revealed text." },
      { key: "smoothing", label: "Smoothing", type: "slider", default: 10, min: 2, max: 40, step: 1, description: "How much the smear lags the cursor. Lower trails further." },
      { key: "sizeFromSpeed", label: "Size From Speed", type: "slider", default: 20, min: 5, max: 60, step: 5, description: "How much faster movement widens the smear." },
      { key: "blur", label: "Goo Blur", type: "slider", default: 25, min: 5, max: 60, step: 1, description: "Blur feeding the goo filter. Higher fuses stamps more." },
      { key: "expandMultiplier", label: "Expand", type: "slider", default: 200, min: 100, max: 400, step: 10, description: "How far each stamp swells before dissolving." },
      { key: "expandTime", label: "Expand Time", type: "slider", default: 2, min: 1, max: 5, step: 1, description: "Seconds a stamp takes to swell." },
      { key: "dissolveTime", label: "Dissolve Time", type: "slider", default: 3, min: 1, max: 8, step: 1, description: "Seconds a stamp takes to disappear." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-barlow-condensed), sans-serif", description: "Typeface for both layers." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the text." },
    ],
  },
  {
    key: "fluid-cursor",
    name: "Fluid Cursor",
    category: "Background",
    blurb: "A real fluid simulation running on the GPU: the cursor injects ink that swirls and dissipates, inverting the type it crosses through difference blending.",
    features: [
      "A full Navier-Stokes solve each frame, advecting velocity, computing curl and divergence, then relaxing pressure over 40 Jacobi iterations to keep the flow incompressible",
      "Vorticity confinement feeds the curl back into the velocity field, which is what keeps the eddies alive instead of smearing flat",
      "The display pass thresholds the dye into flat ink, so the result reads as liquid type rather than a smoke plume",
    ],
    controls: [
      { key: "lines", label: "Headline Lines", type: "textList", default: ["Fluid System In", "Constant Field", "Of Interaction"], description: "Lines of the headline." },
      { key: "brand", label: "Brand", type: "text", default: "Vortex", description: "Wordmark in the nav." },
      { key: "navItems", label: "Nav Items", type: "textList", default: ["works", "about", "updates", "start a project"], description: "Links in the nav." },
      { key: "background", label: "Background", type: "color", default: "#ffffff", description: "Colour of the page. The ink blends against it with difference." },
      { key: "textColor", label: "Text Color", type: "color", default: "#000000", description: "Colour of the headline and nav." },
      { key: "inkColor", label: "Ink Color", type: "color", default: "#ffffff", description: "Colour of the fluid." },
      { key: "curl", label: "Curl", type: "slider", default: 50, min: 0, max: 100, step: 5, description: "How strongly eddies are kept spinning." },
      { key: "splatRadius", label: "Splat Radius", type: "slider", default: 30, min: 5, max: 80, step: 5, description: "Size of the ink the cursor injects." },
      { key: "forceStrength", label: "Force", type: "slider", default: 85, min: 20, max: 200, step: 5, description: "How hard the cursor pushes the fluid." },
      { key: "threshold", label: "Threshold", type: "slider", default: 100, min: 20, max: 200, step: 5, description: "How much dye is needed before ink shows." },
      { key: "edgeSoftness", label: "Edge Softness", type: "slider", default: 0, min: 0, max: 50, step: 5, description: "Softness of the ink edge. Zero is a hard cut." },
      { key: "simResolution", label: "Sim Resolution", type: "slider", default: 256, min: 64, max: 512, step: 64, description: "Resolution of the velocity field. Higher costs more." },
      { key: "dyeResolution", label: "Dye Resolution", type: "slider", default: 1024, min: 256, max: 2048, step: 256, description: "Resolution of the ink. Higher is sharper." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-inter), sans-serif", description: "Typeface for the headline and wordmark." },
      { key: "navFont", label: "Nav Font", type: "font", default: "var(--font-dm-mono), monospace", description: "Typeface for the nav links." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the text." },
    ],
  },
  {
    key: "access-gate-reveal",
    name: "Access Gate Reveal",
    category: "Animations",
    blurb: "A loading ring draws itself in uneven jumps, waits for a click, then unwinds and sweeps the whole gate aside to reveal the headline assembling word by word.",
    features: [
      "The progress ring advances in uneven steps with randomised pauses, so the load reads as real work rather than a constant sweep",
      "The button only becomes live once its label has finished arriving, so the gate cannot be opened mid-load",
      "On exit the ring unwinds past zero and two clip-paths sweep left in sequence, so the gate leaves before the page beneath finishes scaling",
    ],
    controls: [
      { key: "headline", label: "Headline", type: "text", default: "The system is now visible", description: "Revealed word by word after the gate opens." },
      { key: "status", label: "Status", type: "text", default: "Initiating", description: "Line at the top of the gate." },
      { key: "meta", label: "Readout", type: "textList", default: ["Phase 01", "Sequence", "Signal Scan", "07 Layers", "PX-17"], description: "Small readout lines along the bottom." },
      { key: "buttonLabel", label: "Button Label", type: "text", default: "Click to Enter", description: "Call to action shown in the ring once it has filled. It pulses until clicked." },
      { key: "grantedLabel", label: "Granted Label", type: "text", default: "Access Granted", description: "Label shown as the gate opens." },
      { key: "logo", label: "Logo", type: "image", default: "/access-gate/logo-light.png", description: "Mark inside the ring while loading." },
      { key: "backdropLogo", label: "Backdrop Logo", type: "image", default: "/access-gate/logo.png", description: "Mark on the layer revealed behind the gate." },
      { key: "backdropText", label: "Backdrop Text", type: "color", default: "#7a7a7a", description: "Colour of the readout on the layer behind the gate." },
      { key: "background", label: "Background", type: "color", default: "#000000", description: "Colour of the gate and page." },
      { key: "foreground", label: "Foreground", type: "color", default: "#ffffff", description: "Colour of the text, ring and sweep." },
      { key: "trackColor", label: "Ring Track", type: "color", default: "#2b2b2b", description: "Colour of the unfilled ring." },
      { key: "fontFamily", label: "Headline Font", type: "font", default: "var(--font-barlow-condensed), sans-serif", description: "Typeface for the headline." },
      { key: "monoFont", label: "Readout Font", type: "font", default: "'Geist Mono', var(--font-commit-mono), monospace", description: "Typeface for the readout lines and button labels." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of all text." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of the load and reveal." },
    ],
  },
  {
    key: "sticky-flip-cards",
    name: "Sticky Flip Cards",
    category: "Scroll",
    blurb: "A stack of cards rises into a pinned hero, flips as one to reveal its back faces, then peels away card by card in reverse order as the scroll continues.",
    features: [
      "One scroll range is divided into four phases (enter, flip, hold, dismiss) by a table of svh offsets, so retiming the whole sequence means changing one number",
      "Cards leave in reverse order, each over its own slice of the scroll, so the top card peels off first and the stack unpacks rather than scattering",
      "The flip is an elastic tween while the dismiss is scrub-driven, and the dismiss picks up the exact tilt the tween lands on so the two never fight",
      "Card text colour is derived from each card's own background luminance, so new colours stay readable without another control",
    ],
    controls: [
      { key: "headline", label: "Headline", type: "text", default: "Scroll down and watch everything fall into place", description: "Hero line that rises away as the cards arrive." },
      { key: "frontTitle", label: "Front Title", type: "text", default: "First Frame", description: "Heading on the card facing you at the start." },
      { key: "frontBadge", label: "Front Badge", type: "text", default: "Start here", description: "Small pill on the front card." },
      { key: "frontBody", label: "Front Body", type: "text", default: "A single moment, held in place before everything begins to move.", description: "Paragraph on the front card." },
      { key: "aboutText", label: "About Text", type: "text", default: "A quiet progression of motion and stillness, where each layer reveals itself with intention and nothing feels out of place.", description: "Closing section that scrolls up once the cards have cleared." },
      { key: "cardTitles", label: "Card Titles", type: "textList", default: ["Final Hold", "Layered Time", "Weight & Flow", "Soft Motion"], description: "One card is created per title." },
      { key: "cardBodies", label: "Card Bodies", type: "textList", default: ["Everything settles into place, leaving a lasting frame that feels complete.", "Moments stack, overlap, and reveal themselves slowly as the scroll continues.", "Elements carry presence, easing in and out with balance, never rushed, never still.", "Subtle shifts and gentle transitions that build a quiet sense of rhythm as you move forward."], description: "Paired with the titles by position." },
      { key: "cardColors", label: "Card Colors", type: "textList", default: ["#fd4400", "#e7ebdf", "#2668fd", "#fdcb40"], description: "Hex colour per card, cycled if there are fewer than cards." },
      { key: "frontColor", label: "Front Color", type: "color", default: "#fd4400", description: "Background of the card facing you at the start." },
      { key: "background", label: "Background", type: "color", default: "#fbfff2", description: "Colour behind the hero." },
      { key: "aboutBackground", label: "About Background", type: "color", default: "#e7ebdf", description: "Colour of the closing section." },
      { key: "textColor", label: "Text Color", type: "color", default: "#0f0f0f", description: "Colour of the hero headline." },
      { key: "fontFamily", label: "Display Font", type: "font", default: "var(--font-barlow-condensed), sans-serif", description: "Typeface for the headline and card titles." },
      { key: "bodyFont", label: "Body Font", type: "font", default: "var(--font-dm-sans), sans-serif", description: "Typeface for the card paragraphs." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of all text." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "How far each scroll notch advances the sequence." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: false, description: "Run the sequence on a loop instead of waiting for scroll." },
    ],
  },
  {
    key: "overlay-menu",
    name: "Overlay Menu",
    category: "Navigation",
    blurb: "Four coloured panels sweep down one after another, the menu unmasks itself behind them, and every link rises into place line by line.",
    features: [
      "Four panels share one staggered tween, so the overlay arrives as layered colour rather than a single flat wipe",
      "The menu's clip-path opens while the last panel is still moving, which is what makes the panels read as depth instead of steps",
      "Links are split into masked lines and animated per group, so the three columns arrive in their own rhythm",
      "SplitText runs only once fonts have settled, so masked lines are never measured against a fallback face",
    ],
    controls: [
      { key: "heroImage", label: "Hero Image", type: "image", default: "/overlay-menu/hero.jpg", description: "Photo behind the menu." },
      { key: "logo", label: "Logo", type: "image", default: "/overlay-menu/logo.png", description: "Mark in the top left." },
      { key: "socials", label: "Social Links", type: "textList", default: ["Bluesky", "Pinterest", "YouTube", "Instagram", "LinkedIn", "X"], description: "First column, upper block." },
      { key: "legal", label: "Legal Links", type: "textList", default: ["Cookie Policy", "Accessibility", "Data Rights", "Disclosures"], description: "First column, lower block." },
      { key: "primaryLinks", label: "Primary Links", type: "textList", default: ["Home", "Experiments", "Latest Updates", "Documentation", "Community"], description: "Large links in the second column." },
      { key: "secondaryLinks", label: "Secondary Links", type: "textList", default: ["Playground", "Build Something", "Activity Feed", "Profile"], description: "Smaller links beside the primary ones." },
      { key: "panelColors", label: "Panel Colors", type: "textList", default: ["#57cea5", "#063124", "#0b5c43", "#21ba80"], description: "One panel sweeps down per colour, in order." },
      { key: "menuColor", label: "Menu Color", type: "color", default: "#084331", description: "Background of the menu itself." },
      { key: "linkColor", label: "Link Color", type: "color", default: "#ffffff", description: "Colour of the links." },
      { key: "mutedColor", label: "Muted Color", type: "color", default: "#318b6f", description: "Colour of the legal links." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-plus-jakarta-sans), sans-serif", description: "Typeface for the menu." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the links." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of the open and close." },
    ],
  },
  {
    key: "ripple-slider",
    name: "Ripple Slider",
    category: "Sliders",
    blurb: "Click and a shockwave races out from the centre, bending the picture as it goes and leaving the next slide behind it.",
    features: [
      "A single expanding ring both displaces the pixels and wipes between the two textures, so the distortion and the swap are one effect rather than two",
      "The wave's brightness is tied to its own decay, giving the crest a highlight that fades with distance",
      "The shader letterboxes the image itself, so the frame keeps its aspect ratio without any layout maths",
      "Input re-arms at 70% of the wave rather than on completion, so rapid clicks stay responsive",
      "Title and copy sit in difference blend mode, so they stay legible over every frame",
    ],
    controls: [
      { key: "images", label: "Images", type: "imageList", default: ["/ripple-slider/slider-img-1.jpg", "/ripple-slider/slider-img-2.jpg", "/ripple-slider/slider-img-3.jpg", "/ripple-slider/slider-img-4.jpg"], description: "Slides, advanced on click." },
      { key: "titles", label: "Titles", type: "textList", default: ["Blackwater '91", "Crimson Theory", "Tape Delay Archives", "Exit 14 Westbound"], description: "Paired with the images by position." },
      { key: "descriptions", label: "Descriptions", type: "textList", default: ["Flickering lanterns and twisted masks welcome unwanted visitors into a strange celebration beyond the forest trail.", "A mysterious performer slowly loses reality beneath violent lights and unsettling mirrored reflections inside an empty theater.", "Stacks of dusty videotapes and glowing static fill the room during another endless night without a single moment of sleep.", "Heavy rain crashes against the windshield as terrified passengers race through midnight highways without knowing who follows."], description: "Paragraph shown beside each slide." },
      { key: "background", label: "Background", type: "color", default: "#e0ddcf", description: "Colour around the framed image." },
      { key: "waveFrequency", label: "Wave Frequency", type: "slider", default: 25, min: 5, max: 60, step: 1, description: "Number of ripples inside the wave front." },
      { key: "waveStrength", label: "Wave Strength", type: "slider", default: 35, min: 0, max: 120, step: 5, description: "How far the ripple pushes the pixels." },
      { key: "waveWidth", label: "Wave Width", type: "slider", default: 50, min: 10, max: 100, step: 5, description: "Thickness of the travelling band." },
      { key: "falloff", label: "Falloff", type: "slider", default: 10, min: 2, max: 30, step: 1, description: "How quickly the ripple settles behind the front." },
      { key: "boostStrength", label: "Highlight", type: "slider", default: 50, min: 0, max: 150, step: 5, description: "Brightness of the crest." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-host-grotesk), sans-serif", description: "Typeface for the title and copy." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the text." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of the wave and text." },
    ],
  },
  {
    key: "scroll-wave-gallery",
    name: "Scroll Wave Gallery",
    category: "Scroll",
    blurb: "Images drift left and right on three stacked sine waves as they cross the frame, and each one unmasks from its edges as it reaches the middle.",
    features: [
      "Three sine layers of different frequency and speed are summed per image, so the column snakes instead of repeating",
      "Each image reads its own travel across the frame, so its position depends on where it is rather than on a shared clock",
      "The inset clip-path is driven by distance from the centre squared, so pictures open at the middle and close at both edges",
      "The last quarter of the run shrinks progressively, which tapers the column as it leaves",
    ],
    controls: [
      { key: "images", label: "Images", type: "imageList", default: ["/scroll-wave/img1.jpg", "/scroll-wave/img2.jpg", "/scroll-wave/img3.jpg", "/scroll-wave/img4.jpg", "/scroll-wave/img5.jpg", "/scroll-wave/img6.jpg", "/scroll-wave/img7.jpg", "/scroll-wave/img8.jpg", "/scroll-wave/img9.jpg", "/scroll-wave/img10.jpg", "/scroll-wave/img11.jpg", "/scroll-wave/img12.jpg"], description: "Pictures in the column, in order." },
      { key: "intro", label: "Intro", type: "text", default: "Loose Structure", description: "Heading above the gallery." },
      { key: "outro", label: "Outro", type: "text", default: "Thanks for scrolling", description: "Heading below the gallery." },
      { key: "background", label: "Background", type: "color", default: "#e3e4d8", description: "Colour behind everything." },
      { key: "textColor", label: "Text Color", type: "color", default: "#000000", description: "Colour of the headings." },
      { key: "baseAmp", label: "Base Sway", type: "slider", default: 10, min: 0, max: 40, step: 1, description: "Amplitude of the slow swing." },
      { key: "flowAmp", label: "Flow Sway", type: "slider", default: 15, min: 0, max: 40, step: 1, description: "Amplitude of the faster wave." },
      { key: "detailAmp", label: "Detail Sway", type: "slider", default: 2.5, min: 0, max: 15, step: 0.5, description: "Amplitude of the fine wobble." },
      { key: "clipMax", label: "Edge Mask", type: "slider", default: 20, min: 0, max: 45, step: 1, description: "How far the pictures close at the top and bottom of the frame." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-instrument-serif), serif", description: "Typeface for the headings." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the headings." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "How far each scroll notch travels." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: false, description: "Scroll the column on a loop." },
    ],
  },
  {
    key: "spiral-image-gallery",
    name: "Spiral Image Gallery",
    category: "3D",
    blurb: "Photographs are wrapped into one continuous descending helix that turns slowly on its own, spins with your scroll, and leans toward the pointer.",
    features: [
      "Every tile is a bespoke curved mesh whose top and bottom edges are computed from its neighbours, so the ribbon has no seams as its radius tightens",
      "Tiles are laid out from a running table of edge heights rather than a fixed step, which keeps the descent even while the spiral narrows",
      "The fragment shader dims each tile by how squarely it faces the camera, giving the ribbon depth without a single light in the scene",
      "Scroll drives the camera down the helix while scroll velocity adds spin that decays on its own",
    ],
    controls: [
      { key: "images", label: "Images", type: "imageList", default: ["/spiral-gallery/img1.jpg", "/spiral-gallery/img2.jpg", "/spiral-gallery/img3.jpg", "/spiral-gallery/img4.jpg", "/spiral-gallery/img5.jpg", "/spiral-gallery/img6.jpg", "/spiral-gallery/img7.jpg", "/spiral-gallery/img8.jpg", "/spiral-gallery/img9.jpg", "/spiral-gallery/img10.jpg"], description: "Cycled around the helix in order." },
      { key: "headline", label: "Headline", type: "text", default: "Somewhere between structure and disorder new forms quietly start to emerge", description: "Type the spiral passes in front of." },
      { key: "aboutText", label: "About Text", type: "text", default: "New forms begin here", description: "Closing section below the spiral." },
      { key: "background", label: "Background", type: "color", default: "#242424", description: "Colour behind the spiral." },
      { key: "aboutBackground", label: "About Background", type: "color", default: "#171717", description: "Colour of the closing section." },
      { key: "textColor", label: "Text Color", type: "color", default: "#d2d2d2", description: "Colour of the headline." },
      { key: "tilesPerRevolution", label: "Tiles Per Turn", type: "slider", default: 15, min: 6, max: 30, step: 1, description: "How many tiles complete one revolution." },
      { key: "revolutions", label: "Revolutions", type: "slider", default: 5, min: 1, max: 10, step: 1, description: "Length of the helix in turns." },
      { key: "startRadius", label: "Start Radius", type: "slider", default: 5, min: 2, max: 10, step: 0.5, description: "Width of the spiral at the top." },
      { key: "endRadius", label: "End Radius", type: "slider", default: 3.5, min: 1, max: 10, step: 0.5, description: "Width of the spiral at the bottom." },
      { key: "spiralGap", label: "Gap", type: "slider", default: 35, min: 0, max: 150, step: 5, description: "Spacing between successive turns." },
      { key: "spinSpeed", label: "Idle Spin", type: "slider", default: 100, min: 0, max: 400, step: 10, description: "How fast the spiral turns on its own." },
      { key: "parallaxStrength", label: "Parallax", type: "slider", default: 10, min: 0, max: 40, step: 1, description: "How far the spiral leans toward the pointer." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-host-grotesk), sans-serif", description: "Typeface for the headline." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of the headline." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "How far each scroll notch descends." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: false, description: "Travel the spiral on a loop." },
    ],
  },
  {
    key: "stroke-page-transition",
    name: "Stroke Page Transition",
    category: "Transitions",
    blurb: "Two hand-drawn strokes scribble themselves across the screen and swell until they blanket the page, then keep travelling and thin back out to reveal the next one.",
    features: [
      "The cover is drawn with stroke-dashoffset, so one path both draws itself on and travels off without ever being redrawn",
      "Stroke width is tweened alongside the draw, so a line thickens into a full-page cover and thins back to a line",
      "The exit continues in the same direction rather than reversing, so the two halves read as one pass rather than a wipe and its undo",
      "The SVG is scaled past the frame, so stroke ends and caps stay outside the visible area",
    ],
    controls: [
      { key: "pages", label: "Pages", type: "textList", default: ["Home", "About", "Contact"], description: "Nav entries; each shows its own name as the page title." },
      { key: "strokeOne", label: "Stroke One", type: "color", default: "#d8d9d7", description: "Colour of the leading stroke." },
      { key: "strokeTwo", label: "Stroke Two", type: "color", default: "#6e44ff", description: "Colour of the trailing stroke." },
      { key: "background", label: "Background", type: "color", default: "#f0f2ef", description: "Colour of the page." },
      { key: "textColor", label: "Text Color", type: "color", default: "#171717", description: "Colour of the page title and nav." },
      { key: "strokeWidth", label: "Stroke Width", type: "slider", default: 200, min: 50, max: 500, step: 10, description: "Thickness of the strokes at rest." },
      { key: "coverWidth", label: "Cover Width", type: "slider", default: 700, min: 300, max: 1400, step: 50, description: "Thickness the strokes swell to while covering the page." },
      { key: "fontFamily", label: "Display Font", type: "font", default: "var(--font-barlow-condensed), sans-serif", description: "Typeface for the page title." },
      { key: "navFont", label: "Nav Font", type: "font", default: "var(--font-dm-sans), sans-serif", description: "Typeface for the nav." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of all text." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "Playback speed of the transition." },
    ],
  },
  {
    key: "waabi-scroll-reveal",
    name: "Waabi Scroll Reveal",
    category: "Scroll",
    blurb: "A full-bleed hero holds while its headline slides away and its copy lights up word by word, then the photo shrinks to a thumbnail and drifting columns of images take over.",
    features: [
      "Four phases share one pinned scroll range, each reading its own slice of the progress so they overlap the way the reference stages them",
      "Copy is lit word by word from a single progress value, with each word owning an equal slice, so the sentence assembles at a steady rate",
      "The hero photo animates width and height rather than scale, so it crops toward its subject instead of shrinking the whole frame",
      "Four columns drift at two different rates, which separates the near and far pairs as they pass",
    ],
    controls: [
      { key: "heroImage", label: "Hero Image", type: "image", default: "/waabi-scroll/hero.jpg", description: "Full-bleed photo that shrinks to a thumbnail." },
      { key: "gallery", label: "Gallery", type: "imageList", default: ["/waabi-scroll/img1.jpg", "/waabi-scroll/img2.jpg", "/waabi-scroll/img3.jpg", "/waabi-scroll/img4.jpg", "/waabi-scroll/img5.jpg", "/waabi-scroll/img6.jpg", "/waabi-scroll/img7.jpg", "/waabi-scroll/img8.jpg", "/waabi-scroll/img9.jpg", "/waabi-scroll/img10.jpg", "/waabi-scroll/img11.jpg", "/waabi-scroll/img12.jpg", "/waabi-scroll/img13.jpg", "/waabi-scroll/img14.jpg", "/waabi-scroll/img15.jpg", "/waabi-scroll/img16.jpg"], description: "Split evenly across the four drifting columns." },
      { key: "headline", label: "Headline", type: "text", default: "A study of motion unfolding inside a single frame", description: "Hero line that slides up and away first." },
      { key: "copy", label: "Copy", type: "text", default: "The moment where stillness transforms into movement", description: "Lit one word at a time as the scroll continues." },
      { key: "aboutText", label: "About Text", type: "text", default: "Fragments of motion and atmosphere gathered into a drifting collection of quiet visual moments.", description: "Centred between the drifting columns." },
      { key: "outro", label: "Outro", type: "text", default: "The frame settles back into quiet stillness.", description: "Closing line." },
      { key: "background", label: "Background", type: "color", default: "#e3e3db", description: "Colour behind the gallery." },
      { key: "outroBackground", label: "Outro Background", type: "color", default: "#cecec6", description: "Colour of the closing panel." },
      { key: "textColor", label: "Text Color", type: "color", default: "#000000", description: "Colour of the gallery and outro text." },
      { key: "heroTextColor", label: "Hero Text Color", type: "color", default: "#ffffff", description: "Colour of the text over the photo." },
      { key: "finalImageSize", label: "Final Size", type: "slider", default: 150, min: 60, max: 400, step: 10, description: "Size in pixels the hero photo shrinks to." },
      { key: "tileGap", label: "Tile Gap", type: "slider", default: 5, min: 0, max: 40, step: 1, description: "Space in pixels between the images stacked in each column." },
      { key: "fontFamily", label: "Font", type: "font", default: "var(--font-inter), sans-serif", description: "Typeface throughout." },
      { key: "textScale", label: "Text Scale", type: "fontScale", default: 100, min: 50, max: 200, step: 10, description: "Relative size of all text." },
      { key: "speed", label: "Speed", type: "slider", default: 100, min: 50, max: 200, step: 10, description: "How far each scroll notch advances." },
      { key: "autoPlay", label: "Auto Play", type: "toggle", default: false, description: "Run the sequence on a loop." },
    ],
  },
];

export function getOriginal(key: string): OriginalEntry | undefined {
  return ORIGINALS.find((o) => o.key === key);
}

export function getOriginalDefaults(key: string): Params {
  const o = getOriginal(key);
  return o ? defaultsFrom(o.controls) : {};
}
